### ISSUE TITLE
Consolidate Tutorial

### ISSUE THREAD

**Issue by pboardman** [chudeki8/lainet-docs#1]
I think that putting everything in separate page named "Step X" makes it hard to navigate. I think we should make one page named something like "Setting up your node" with everything in it. This would make it easier for people if they need to search for specific part of the tutorial.

And maybe we could put the firewall part in another category. I think it makes the tutorial overly complex because most people don't have their port blocked directly on their machine anyway. (and those who do know how to open them)

**Comment by chudeki8** [comment]
That's good advice, I was basically doing a brain dump of stuff while it was still fresh. Sorry I took almost a week to see this issue.

How would this look?
- install
- peering
- nodes at home
- basic firewall tips (mostly for services)
- gateway

**Comment by pboardman** [comment]
It would look a lot better I think.

By the way, in part 7 you say: 
`You'll need to add their password to "authorizedPasswords":`
You don't have to do that.

**Comment by chudeki8** [comment]
OK, just changed the wiki pages. Is the peering section correct?

I was a little unsure about that. I definitely messed it up the first time.

**Comment by pboardman** [comment]
hmm looks good, but at the end of `installing`, you are suposed to enter your peer name in the password not yours. (Also, maybe this last part `Edit Password` should be in the peering page). 

I never had to do any ipv6 forwarding with my node at home so I don't know how useful this part of `Nodes at home` is but we can keep it there anyway.

Good work with the tutorial. It should be easy enough to follow for people new to CJDNS.
